import BreadCrumb from "@/components/common/breadcrumb/breadcrumb"
import SubBannerMenu from "@/components/common/sub-menu-banner";
import CategoryMenu from "@/components/common/CategoryMenu";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MenuLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <CategoryMenu />
      <div className="w-full flex justify-center">
        <div className="w-[1100px] h-auto pb-[100px]">
          <BreadCrumb />
          {children}
        </div>
      </div>
    </>
  );
}
